### ISSUE TITLE
Make it a template repository

### ISSUE THREAD

**Issue by elliotfontaine** [vitallium/zed-extension-template#1]
https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository

**Comment by vitallium** [comment]
Hi. I initially thought about doing that, but GitHub's templating support is not good enough when it comes to customization. For instance, I would like to offer the user a choice between having a grammar or just an LSP for the extension. But I will re-evaluate that decision if it makes things easier for the end user.

**Comment by elliotfontaine** [comment]
> But I will re-evaluate that decision if it makes things easier for the end user.

My bad, I didn't know about `cargo-generate`. I initially thought it was based on "Liquid" because of **extension.toml.liquid**, which doesn't seem to target end users. So ended up replacing all the `{{ template variables }}` manually. 🫠

The repo tag is easy to miss, maybe you could change the About of the repo to:
_"A **cargo-generate** template for creating a new extension for Zed editor"_

**Comment by vitallium** [comment]
>The repo tag is easy to miss, maybe you could change the About of the repo to:

Yeah, that's a good idea! Changed that.

>My bad, I didn't know about cargo-generate. I initially thought it was based on "Liquid" because of extension.toml.liquid, which doesn't seem to target end users. So ended up replacing all the {{ template variables }} manually. 🫠

I still wonder how to make this repo available for GitHub's templating feature, as that would make it easier to start your own Zed extension. Probably by using different branches or something else.
